name: cross_link
description: Cross-Link mobile app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.3+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  amplify_auth_cognito: ^1.0.1
  amplify_flutter: ^1.0.1
  amplify_push_notifications_pinpoint: ^1.0.0
  dio: ^5.3.1
  equatable: ^2.0.5
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.3
  firebase_ui_auth: ^1.4.0
  flutter_bloc: ^8.1.3
  flutter_blue_plus: ^1.15.5
  flutter_bluetooth_serial: ^0.4.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_it: ^7.6.0
  google_sign_in: ^6.1.5
  intl: ^0.17.0
  permission_handler: ^11.0.0
  retrofit: ^4.0.1
  #syncfusion_flutter_charts: 21.2.5
  syncfusion_flutter_charts: 20.3.50

  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  retrofit_generator: ^7.0.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/

